
services:
  # frontend:
  #   build:
  #     context: ./frontend/
  #     dockerfile: dockerfile.frontend 
  #   image: frontend:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/home/app:z

  #   command: npm start
  backend:
    build:
      context: ./backend/
      dockerfile: docker/dockerfile.backend
    image: backend:latest
    ports:
      - "9000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/home/app:z
    command: >
      /bin/sh -c "
        echo 'Waiting for PostgreSQL to be ready...' &&
        sleep 10 &&
        echo 'Running migrations...' &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    restart: always
    depends_on:
      - database
      - geoserver
    

  # fast_api:
  #   build:
  #     context: ./fast_api
  #     dockerfile: Dockerfile
  #   image: fast_m:latest
  #   ports:
  #     - "7100:7100"
  #   env_file:
  #     - ./fast_api/.fastmdb.env
  #   volumes:
  #     - ./fast_api:/home/app:z
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 7100 --reload
  #   restart: always
  #   depends_on:
  #     - database
  #     - geoserver   


  # db:
  #   image: postgres:15-alpine
  #   ports:
  #     - "5440:5432"
  #   restart: always
  #   expose:
  #     - "5440"
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  database:
    image: postgres:16
    ports:
      - "5450:5432"
    env_file:
      - ./database/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:z
    restart: always
    depends_on:
      - geoserver


  geoserver:
    image: kartoza/geoserver:2.28.0
    ports:
      - "9090:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ./backend/media:/opt/geoserver/medias
    environment:
      ENABLE_CORS: "true"
      CORS_ENABLED: "true"
      CORS_ALLOWED_ORIGINS: http://localhost:3000,https://*.slcrdss.in,https://*.slcrdss.xyz
      CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE,HEAD,OPTIONS
      CORS_ALLOWED_HEADERS: "*"
      TOMCAT_EXTRAS: "true"
      HTTP_MAX_HEADER_SIZE: 33554432
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
    env_file:
      - ./fast_api/.fastmdb.env
    restart: always    

volumes:
  postgres_data:
  geoserver_data: