"""fresh

Revision ID: f011904190e6
Revises: 
Create Date: 2026-04-06 07:18:32.150973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f011904190e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_basic_state',
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('state_code')
    )
    op.create_table('dummy',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=40), nullable=False),
    sa.Column('population_1951', sa.BigInteger(), nullable=False),
    sa.Column('population_1961', sa.BigInteger(), nullable=False),
    sa.Column('population_1971', sa.BigInteger(), nullable=False),
    sa.Column('population_1981', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('subdistrict_code')
    )
    op.create_table('basic_basic_district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=40), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['basic_basic_state.state_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('district_code')
    )
    op.create_index(op.f('ix_basic_basic_district_state_code'), 'basic_basic_district', ['state_code'], unique=False)
    op.create_table('basic_basic_subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(length=40), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['basic_basic_district.district_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subdistrict_code')
    )
    op.create_index(op.f('ix_basic_basic_subdistrict_district_code'), 'basic_basic_subdistrict', ['district_code'], unique=False)
    op.create_table('basic_basic_village',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(length=100), nullable=False),
    sa.Column('population_2011', sa.Integer(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['basic_basic_subdistrict.subdistrict_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('village_code')
    )
    op.create_index(op.f('ix_basic_basic_village_subdistrict_code'), 'basic_basic_village', ['subdistrict_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basic_basic_village_subdistrict_code'), table_name='basic_basic_village')
    op.drop_table('basic_basic_village')
    op.drop_index(op.f('ix_basic_basic_subdistrict_district_code'), table_name='basic_basic_subdistrict')
    op.drop_table('basic_basic_subdistrict')
    op.drop_index(op.f('ix_basic_basic_district_state_code'), table_name='basic_basic_district')
    op.drop_table('basic_basic_district')
    op.drop_table('dummy')
    op.drop_table('basic_basic_state')
    # ### end Alembic commands ###
