"""new updates 

Revision ID: ebb8a35d397d
Revises: 
Create Date: 2026-04-22 10:13:24.119485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb8a35d397d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stp_suitability_raster',
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('raster_category', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stp_suitability_raster_id'), 'stp_suitability_raster', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stp_suitability_raster_id'), table_name='stp_suitability_raster')
    op.drop_table('stp_suitability_raster')
    # ### end Alembic commands ###
