from django.urls import path

from .views import (
    analysis_dem_slope,
    analysis_dem_slope_clip,
    analysis_flow_direction,
    analysis_flow_direction_clip,
    analysis_groundwater,
    analysis_groundwater_clip,
    analysis_nirmal_gwq_clip,
    analysis_nirmal_rwq_clip,
    analysis_nirmal_rwq_stats,
    analysis_nirmal_stp,
    analysis_rainfall,
    analysis_rainfall_clip,
    analysis_tributary_drain,
    analysis_zone_raster,
    analysis_zone_raster_clip,
    location_district,
    location_state,
)

urlpatterns = [
    path("location/state", location_state, name="holistic-location-state"),
    path("location/district", location_district, name="holistic-location-district"),
    path("analysis/zone-raster", analysis_zone_raster, name="holistic-analysis-zone-raster"),
    path("analysis/zone-raster-clip", analysis_zone_raster_clip, name="holistic-analysis-zone-raster-clip"),
    path("analysis/rainfall", analysis_rainfall, name="holistic-analysis-rainfall"),
    path("analysis/groundwater", analysis_groundwater, name="holistic-analysis-groundwater"),
    path("analysis/tributary-drain", analysis_tributary_drain, name="holistic-analysis-tributary-drain"),
    path("analysis/dem-slope", analysis_dem_slope, name="holistic-analysis-dem-slope"),
    path("analysis/dem-slope-clip", analysis_dem_slope_clip, name="holistic-analysis-dem-slope-clip"),
    path("analysis/rainfall-clip", analysis_rainfall_clip, name="holistic-analysis-rainfall-clip"),
    path("analysis/groundwater-clip", analysis_groundwater_clip, name="holistic-analysis-groundwater-clip"),
    path("analysis/flow-direction", analysis_flow_direction, name="holistic-analysis-flow-direction"),
    path("analysis/flow-direction-clip", analysis_flow_direction_clip, name="holistic-analysis-flow-direction-clip"),
    path("analysis/nirmal-gwq-clip", analysis_nirmal_gwq_clip, name="holistic-analysis-nirmal-gwq-clip"),
    path("analysis/nirmal-rwq-clip", analysis_nirmal_rwq_clip, name="holistic-analysis-nirmal-rwq-clip"),
    path("analysis/nirmal-rwq-stats", analysis_nirmal_rwq_stats, name="holistic-analysis-nirmal-rwq-stats"),
    path("analysis/nirmal-stp", analysis_nirmal_stp, name="holistic-analysis-nirmal-stp"),
]
